version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@angular/cli"
    versions:
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/forms"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/core"
    versions:
    - 11.2.10
    - 11.2.11
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular-eslint/builder"
    versions:
    - 1.2.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 1.2.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@angular-eslint/template-parser"
    versions:
    - 1.2.0
    - 2.0.1
    - 2.0.2
    - 2.1.0
    - 4.0.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.4
    - 3.6.6
    - 3.6.7
    - 3.6.8
    - 3.6.9
  - dependency-name: karma
    versions:
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
